apiVersion: apps/v1
kind: Deployment
metadata:
  name: sogong-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sogong
  template:
    metadata:
      labels:
        app: sogong
    spec:
      containers:
        - name: sogong
          image: paduck/sogong
